base/urls.py
"""
Django Realtime Chat & Notifications
"""
## @package users.urls
#
# Urls de la aplicación participacion
# @version 1.0
from django.urls import path
from .views import *

app_name = 'base'
urlpatterns = [
    path('', Inicio.as_view(), name = "inicio")
]

django_channels/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import (
    PasswordResetConfirmView, PasswordResetCompleteView
    )
from users.forms import PasswordConfirmForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls', namespace="base")),
    path('', include('users.urls')),
    path('chat/', include('chat.urls')),
    path('user/password/reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(template_name='user.passwordreset.confirm.html',
                                        success_url='/user/password/done/',
                                        form_class=PasswordConfirmForm
                                        ),
        name='password_reset_confirm',
    ),
    path(
        'user/password/done/',
        PasswordResetCompleteView.as_view(template_name='user.passwordreset.end.html'),
        name='pass_done',
    ),
]

users/urls.py
"""
Django Realtime Chat & Notifications
"""
## @package users.urls
#
# Urls de la aplicación participacion
# @version 1.0
from django.urls import path, reverse_lazy
from .views import *
from .forms import PasswordResetForm
from users import views
from django.contrib.auth.views import (
    PasswordResetView, PasswordResetDoneView,
	)

app_name = 'users'
urlpatterns = [
    path('login', LoginView.as_view(), name = "login"),
    path('logout', LogoutView.as_view(), name = "logout"),
    path('register', RegisterView.as_view(), name = "register"),
    path('account/password/reset/', PasswordResetView.as_view(
    								template_name='user.reset.html',
    								success_url=reverse_lazy('users:reset_done'),
    								form_class=PasswordResetForm),
    	name='forgot'),
    path('accounts/password/done/', PasswordResetDoneView.as_view(
    							   template_name='user.passwordreset.done.html'),
        name='reset_done'),
    path('account/change-pass/', ChangePasswordView.as_view(), name="change_pass"),
]

users/models.py
"""
Django Realtime Chat & Notifications
"""
## @package users.models
#
# Modelos correspondientes a los usuarios
# @version 1.0

users/forms.py
"""
Django Realtime Chat & Notifications
"""
## @package users.forms
#
# Formulario correspondiente a la aplicación users
# @version 1.0
from django import forms
from django.forms import ModelForm
from django.contrib.auth import authenticate
from django.contrib.auth.hashers import check_password
from django.contrib.auth.models import User
from django.contrib.auth.forms import (
    UserCreationForm
)
from django.forms.fields import (
    CharField, BooleanField
)
from django.forms.widgets import (
    PasswordInput, CheckboxInput
)
from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm, PasswordChangeForm
from base.functions import (
    validate_email, validate_username
    )
#from captcha.fields import CaptchaField

from django.core.validators import RegexValidator

class LoginForm(forms.Form):
    """!
    Clase del formulario de logeo

    @date 01-03-2017
    @version 1.0.0
    """
    ## Campo de la constraseña
    contrasena = CharField()

    ## Nombre del usuario
    usuario = CharField()

    ## Formulario de recordarme
    remember_me = BooleanField()

    ## Campo del captcha
    #captcha = CaptchaField()

    def __init__(self, *args, **kwargs):
        """!
        Metodo que sobreescribe cuando se inicializa el formulario

        @date 01-03-2017
        @param self <b>{object}</b> Objeto que instancia la clase
        @param args <b>{list}</b> Lista de los argumentos
        @param kwargs <b>{dict}</b> Diccionario con argumentos
        @return Retorna el formulario validado
        """
        super(LoginForm, self).__init__(*args, **kwargs)
        self.fields['contrasena'].widget = PasswordInput()
        self.fields['contrasena'].widget.attrs.update({'class': 'validate',
        'placeholder': 'Contraseña'})
        self.fields['usuario'].widget.attrs.update({'class': 'validate',
        'placeholder': 'Nombre de Usuario'})
        self.fields['remember_me'].label = "Recordar"
        self.fields['remember_me'].widget = CheckboxInput()
        self.fields['remember_me'].required = False
        #self.fields['captcha'].label = "Captcha"
        #self.fields['captcha'].widget.attrs.update({'class': 'validate'})

    def clean(self):
        """!
        Método que valida si el usuario a autenticar es valido

        @date 21-04-2017
        @param self <b>{object}</b> Objeto que instancia la clase
        @return Retorna el campo con los errores
        """
        usuario = self.cleaned_data['usuario']
        contrasena = self.cleaned_data['contrasena']
        usuario = authenticate(username=usuario,password=contrasena)
        if(not usuario):
            msg = "Verifique su usuario o contraseña"
            self.add_error('usuario', msg)

    class Meta:
        fields = ('usuario', 'contrasena', 'remember_me')


class UserRegisterForm(UserCreationForm):
    """!
    Formulario de Registro

    @date 20-04-2017
    @version 1.0.0
    """
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2',
                  'first_name', 'last_name', 'email']

    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)

        self.fields['username'].required = True
        self.fields['username'].label = 'Nombre de Usuario'

        self.fields['password1'].required = True
        self.fields['password1'].label = 'Constraseña'

        self.fields['password2'].required = True
        self.fields['password2'].label = 'Repita su constraseña'

        self.fields['first_name'].label = 'Nombre'

        self.fields['last_name'].label = 'Apellido'

        self.fields['email'].label = 'Correo'

    def clean_password_repeat(self):
        """!
        Método que valida si las contraseñas coinciden

        @date 01-03-2017
        @param self <b>{object}</b> Objeto que instancia la clase
        @return Retorna el campo con la validacion
        """
        password = self.cleaned_data['password1']
        password_repeat = self.cleaned_data['password2']
        if(password_repeat!=password):
            raise forms.ValidationError("La contraseña no coincide")
        return password_repeat

    def clean_email(self):
        """!
        Método que valida si el correo es única

        @date 01-03-2017
        @param self <b>{object}</b> Objeto que instancia la clase
        @return Retorna el campo con la validacion
        """
        email = self.cleaned_data['email']
        if(validate_email(email)):
            raise forms.ValidationError("El correo ingresado ya existe")
        return email


class PasswordResetForm(PasswordResetForm):
    """!
    Clase del formulario de resetear contraseña

    @date 02-05-2017
    @version 1.0.0
    """

    def __init__(self, *args, **kwargs):
        super(PasswordResetForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update({'class': 'form-control',
                                                  'placeholder': 'Correo'})

    def clean(self):
        cleaned_data = super(PasswordResetForm, self).clean()
        email = cleaned_data.get("email")

        if email:
            msg = "Error no existe el email"
            try:
                User.objects.get(email=email)
            except:
                self.add_error('email', msg)



class PasswordConfirmForm(SetPasswordForm):
    """!
    Formulario para confirmar la constraseña

    @date 15-05-2017
    @version 1.0.0
    """
    def __init__(self, *args, **kwargs):
        super(PasswordConfirmForm, self).__init__(*args, **kwargs)
        self.fields['new_password1'].widget.attrs.update({'class': 'input-field',
                                                  'placeholder': 'Contraseña Nueva'})
        self.fields['new_password2'].widget.attrs.update({'class': 'input-field',
                                                  'placeholder': 'Repita su Contraseña'})


class PasswordChangeForms(forms.Form):
    """!
    Formulario de Registro

    @date 20-02-2018
    @version 1.0.0
    """
    ## Antigua Contraseña
    old_password = forms.CharField(max_length=20,
        widget=forms.TextInput(attrs={'type':'password'}),
        label="Antigua contraseña"
        )

    ## Nueva Contraseña
    new_password = forms.CharField(max_length=20,
        widget=forms.TextInput(attrs={'type':'password'}),
        label="Nueva contraseña"
        )

    ## Repita la Nueva Contraseña
    new_password_repeat = forms.CharField(max_length=20,
        widget=forms.TextInput(attrs={'type':'password'}),
        label="Repita su nueva contraseña"
        )


class PasswordChangeAccount(PasswordChangeForm):

    def __init__(self, *args, **kwargs):
        super(PasswordChangeAccount, self).__init__(*args, **kwargs)
        self.fields['old_password'].widget.attrs.update({'class': 'input-field',
                                                  'placeholder': 'Antigua contraseña'})
        self.fields['new_password1'].widget.attrs.update({'class': 'input-field',
                                                  'placeholder': 'Contraseña Nueva'})
        self.fields['new_password2'].widget.attrs.update({'class': 'input-field',
                                                  'placeholder': 'Repita su Contraseña'})     

users/views.py
"""
Django Realtime Chat & Notifications
"""
## @package user.views
#
# Vistas correspondientes a la aplicación usuario
# @version 1.0
from django.shortcuts import render, redirect
from django.views.generic import (
    FormView, RedirectView, CreateView, 
    UpdateView, ListView, TemplateView
    )
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.hashers import check_password
from django.urls import reverse_lazy
from django.contrib.auth.models import User, Group
from django.contrib.auth import login
from django.http import HttpResponseForbidden, JsonResponse
from .forms import (
    LoginForm, UserRegisterForm, 
    PasswordChangeForm, PasswordConfirmForm, PasswordChangeAccount
    )



class LoginView(FormView):
    """!
    Clase que gestiona la vista principal del logeo de usuario

    @date 01-03-2017
    @version 1.0.0
    """
    form_class = LoginForm
    template_name = 'user.login.html'
    success_url = reverse_lazy('base:inicio')

    def form_valid(self, form):
        """!
        Metodo que valida si el formulario es valido
    
        @date 01-03-2017
        @param self <b>{object}</b> Objeto que instancia la clase
        @param form <b>{object}</b> Objeto que contiene el formulario de registro
        @return Retorna el formulario validado
        """
        usuario = form.cleaned_data['usuario']
        contrasena = form.cleaned_data['contrasena']
        usuario = authenticate(username=usuario, password=contrasena)
        login(self.request, usuario)
        if self.request.POST.get('remember_me') is not None:
            # Session expira a los dos meses si no se deslogea
            self.request.session.set_expiry(1209600)
        return super().form_valid(form)
    
    
class LogoutView(RedirectView):
    """!
    Clase que gestiona la vista principal del deslogeo de usuario

    @date 01-03-2017
    @version 1.0.0
    """
    permanent = False
    query_string = True

    def get_redirect_url(self):
        """!
        Metodo que permite definir la url de dirección al ser válido el formulario
    
        @date 01-03-2017
        @param self <b>{object}</b> Objeto que instancia la clase
        @return Retorna la url
        """
        logout(self.request)
        return reverse_lazy('users:login')


class RegisterView(SuccessMessageMixin,CreateView):
    """!
    Muestra el formulario de registro de usuarios

    @date 09-01-2017
    @version 1.0.0
    """
    template_name = "user.register.html"
    form_class = UserRegisterForm
    success_url = reverse_lazy('base:inicio')
    success_message = "Se registró con éxito"
    model = User


class ChangePasswordView(LoginRequiredMixin,FormView):
    """!
    Clase que gestion el cambio de contraseña

    @date 20-02-2018
    @version 1.0.0
    """
    template_name = "change_password.form.html"
    form_class = PasswordChangeAccount
    success_url = reverse_lazy('base:inicio')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        """!
        Metodo que sobreescribe la acción por POST
    
        @date 20-02-2018
        @param self <b>{object}</b> Objeto que instancia la clase
        @param request <b>{object}</b> Objeto que contiene la petición
        @param pk <b>{int}</b> Recibe el id del perfil
        @return Retorna los datos de contexto
        """
        user = form.save()
        try:
            login(self.request, user)
        except:
            return super().form_valid(form)    
        return super().form_valid(form)

users/templates/change_password.form.html
{% extends 'base.template.html' %}
{% block title %}Cambiar Contraseña{% endblock %}
{% block content %}
    <div class="content center">
        <form action="" role="form" class="form form-horizontal validate-form change_form" method="post" autocomplete="off">
            {% csrf_token %}
            <div class="center">
                <h3>Cambiar Contraseña</h3><hr>

                {% for field in form %}
                    <div class="col m12 s12">
                        <div class="input-field {% if field.errors %}invalid{% endif %}">
                            <div class="col m4 s4">
                                <div class="row">
                                    {{ field }}
                                    <label for="{{ field.auto_id }}">
                                        {{ field.label }}
                                    </label>
                                </div>
                                {% include 'base.forms.errors.html' with form_errors=field.errors col_title_error='col s2' col_msg_error='col s10' %}
                            </div>
                        </div>
                    </div><br><br><br>
                {% endfor %}

                 <div class="col-md-12 col-sm-12 col-xs-12">
                    <button type="submit" class="btn waves-effect teal">Cambiar</button>
                 </div>
            </div>
        </form>
    </div>
{% endblock content %}

users/templates/user.login.html
{% extends 'base.template.html' %}
{% load staticfiles %}
{% block title %}Login{% endblock %}
{% block content %}
<div class="content center">
    <form id="form" action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
        <div class="input-field {% if form.usuario.errors %}invalid{% endif %}">
            <i class="tiny material-icons prefix">account_circle</i>
            {{ form.usuario }}
            <label for="icon_prefix {{ form.usuario.auto_id }}">Usuario</label>
            {% include 'base.forms.errors.html' with form_errors=form.usuario.errors col_title_error='col s2' col_msg_error='col s10' %}
        </div>
        
        <div class="input-field {% if form.usuario.errors %}invalid{% endif %}">
            <i class="tiny material-icons prefix">lock</i>
            {{ form.contrasena }}
            <label for="icon_prefix {{ form.contrasena.auto_id }}">Contraseña</label>
            {% include 'base.forms.errors.html' with form_errors=form.usuario.errors col_title_error='col s2' col_msg_error='col s10' %}
        </div>
        
        <div class="row">
            <a href="{% url 'users:register' %}" style="cursor: pointer">Registrarse</a> | 
            <a href="{% url 'users:forgot' %}" style="cursor: pointer">¿Olvido su contraseña?</a>
        </div>
        
        <div class="row">
            <p class="center">
                {{form.remember_me}}
                <label for="id_remember_me">{{form.remember_me.label}}</label>
            </p>
        </div>
        <div class="row" style="display:none">
            <div class="col s4 offset-s5">
                <div class="input-field {% if form.captcha.errors %}invalid{% endif %}">
                    <label>{{form.captcha.label}}</label>
                    <div class="col s7">
                        {{form.captcha}}
                    </div>
                    <a class="col s2" onclick="refresh_captcha(this);" style="cursor: pointer">
                        <i class="small material-icons">cached</i>
                    </a>
                    {% include 'base.forms.errors.html' with form_errors=form.captcha.errors col_title_error='col s2' col_msg_error='col s10' %}
                </div>
            </div>
        </div>
        <div>
            <button type="submit" class="btn waves-effect teal">Entrar</button>
        </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/user.passwordreset.confirm.html
{% extends 'base.template.html' %}
{% load staticfiles %}
{% block title %}Recuperar Contraseña{% endblock %}
{% block content %}
    <div class="center">
        <h1>Confirme su contraseña</h1><hr>
        <form method="post">
            {% csrf_token %}
            <ul>
                <li class="text-left">Su contraseña no puede asemejarse tanto a su otra información personal.</li>
                <li class="text-left">Su contraseña debe contener por lo menos 8 caracteres.</li>
                <li class="text-left">La contraseña no puede ser una contraseña de uso común.</li>
                <li class="text-left">Su contraseña no puede ser completamente numérica.</li>
            </ul><br>

            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="input-field {% if form.new_password1.errors %}invalid{% endif %}">
                    {{ form.new_password1 }}
                    <label for="{{ form.new_password1.auto_id }}">
                        {{ form.new_password1.label }}
                    </label>
                    {% include 'base.forms.errors.html' with form_errors=form.new_password1.errors col_title_error='col s2' col_msg_error='col s10' %}
                </div>
            </div><br><br><br>
          
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="input-field {% if form.new_password2.errors %}invalid{% endif %}">
                    {{ form.new_password2 }}
                    <label for="{{ form.new_password2.auto_id }}">
                        {{ form.new_password2.label }}
                    </label>
                    {% include 'base.forms.errors.html' with form_errors=form.new_password2.errors col_title_error='col s2' col_msg_error='col s10' %}
                </div>
            </div><br><br><br>
            <div class="col-md-12 col-sm-12 col-xs-12">
                <button type="submit" class="btn waves-effect teal">Confirmar</button>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/user.passwordreset.done.html
{% extends 'base.template.html' %}
{% load staticfiles %}
{% block title %}Recuperar Contraseña{% endblock %}
{% block content %}
    <div class="center">
        <h1>Información</h1><hr>
        <p>
            La información para recuperar la <b>constraseña</b> fue enviada al <b>correo</b> suministrado.
        </p>
    </div>
    <a type="button" class="btn waves-effect teal" href="{% url 'base:inicio'%}">Regresar</a>
{% endblock %}

users/templates/user.passwordreset.end.html
{% extends 'base.template.html' %}
{% load staticfiles %}
{% block title %}Recuperar Contraseña{% endblock %}
{% block content %}
    <div class="row text-center">
        <h1>Éxito</h1><hr>
        <p>
            Su contraseña fue cambiada con éxito
        </p><br>
    </div>
    <a type="button" class="btn waves-effect teal" href="{% url 'base:inicio'%}">Regresar</a>
{% endblock %}

users/templates/user.register.html
{% extends 'base.template.html' %}
{% load staticfiles %}
{% block title %}Registrarse{% endblock %}
{% block content %}
  <div class="center">
    <h1>Registro</h1><hr>
    <form action="{% url 'users:register' %}" method="post">
    {% csrf_token %}
      <div class="col m12 s12">
        <div class="input-field {% if form.username.errors %}invalid{% endif %}">
          <div class="col m4 s4">
            {{ form.username }}
            <label for="{{ form.username.auto_id }}">
              {{ form.username.label }}
            </label>
            {% include 'base.forms.errors.html' with form_errors=form.username.errors col_title_error='col s2' col_msg_error='col s10' %}
          </div>
          
        </div>
      </div><br><br><br>
      
       <div class="col m12 s12">
        <div class="input-field {% if form.password1.errors %}invalid{% endif %}">
          <div class="col m4 s4">
            {{ form.password1 }}
            <label for="{{ form.password1.auto_id }}">
              {{ form.password1.label }}
            </label>
            {% include 'base.forms.errors.html' with form_errors=form.password1.errors col_title_error='col s2' col_msg_error='col s10' %}
          </div>
          
        </div>
      </div><br><br><br>
      
      <div class="col m12 s12">
        <div class="input-field {% if form.password2.errors %}invalid{% endif %}">
          <div class="col m4 s4">
            {{ form.password2 }}
            <label for="{{ form.password2.auto_id }}">
              {{ form.password2.label }}
            </label>
            {% include 'base.forms.errors.html' with form_errors=form.password2.errors col_title_error='col s2' col_msg_error='col s10' %}
          </div>
          
        </div>
      </div><br><br><br>
          
      <div class="col m12 s12">
        <div class="input-field {% if form.first_name.errors %}invalid{% endif %}">
          <div class="col m4 s4">
            {{ form.first_name }}
            <label for="{{ form.first_name.auto_id }}">
              {{ form.first_name.label }}
            </label>
            {% include 'base.forms.errors.html' with form_errors=form.first_name.errors col_title_error='col s2' col_msg_error='col s10' %}
          </div>
          
        </div>
      </div><br><br><br>
      
      <div class="col m12 s12">
        <div class="input-field {% if form.last_name.errors %}invalid{% endif %}">
          <div class="col m4 s4">
            {{ form.last_name }}
            <label for="{{ form.last_name.auto_id }}">
              {{ form.last_name.label }}
            </label>
            {% include 'base.forms.errors.html' with form_errors=form.last_name.errors col_title_error='col s2' col_msg_error='col s10' %}
          </div>
          
        </div>
      </div><br><br><br>
          
      <div class="col m12 s12">
        <div class="input-field {% if form.email.errors %}invalid{% endif %}">
          <div class="col m4 s4">
            {{ form.email }}
            <label for="{{ form.email.auto_id }}">
              {{ form.email.label }}
            </label>
            {% include 'base.forms.errors.html' with form_errors=form.email.errors col_title_error='col s2' col_msg_error='col s10' %}
          </div>
          
        </div>
      </div><br><br><br>

      <div class="col m12 s12">
         <a type="button" class="btn waves-effect teal" href="{% url 'base:inicio' %}">Regresar</a>
         <button type="submit" class="btn waves-effect teal">Registrar</button>
      </div>
    </form>
  </div>
  <br />
{% endblock %}

{% block extraJs %}
<script type="text/javascript">
  $('.datepicker').pickadate({
    selectMonths: true,
    selectYears: 15,
    format: 'dd/mm/yyyy'
  });
</script>
{%endblock%}

users/templates/user.reset.html
{% extends 'base.template.html' %}
{% load staticfiles %}
{% block title %}Recuperar Contraseña{% endblock %}
{% block content %}
    <div class="center">
        <h1>Recuperar Contraseña</h1><hr>
        <form method="post">
            {% csrf_token %}
            <div class="col m12 s12">
                <div class="input-field {% if form.email.errors %}invalid{% endif %}">
                    {{ form.email }}
                    <label for="{{ form.email.auto_id }}">
                        {{ form.email.label }}
                    </label>
                    {% include 'base.forms.errors.html' with form_errors=form.email.errors col_title_error='col s2' col_msg_error='col s10' %}
                    <div class="col s1"><i class="ion ion-ios-medical item-requerido"></i></div>
                </div>
            </div><br><br><br>
            <div class="col m12 s12">
                <button type="submit" class="btn waves-effect teal">Enviar</button>
            </div>
        </form>
    </div>

{% endblock %}