base/urls.py
"""
Django Realtime Chat & Notifications
"""
## @package users.urls
#
# Urls de la aplicación participacion
# @version 1.0
from django.urls import path
from .views import *

app_name = 'base'
urlpatterns = [
    path('', Inicio.as_view(), name = "inicio")
]

chat/urls.py
"""
Django Realtime Chat & Notifications
"""
## @package chat.urls
#
# Urls de la aplicación participacion
# @version 1.0
from django.urls import path
from .views import *

app_name = 'chat'
urlpatterns = [
    path('', ChatView.as_view(), name = "chat"),
    path('listar-comentarios', ListComment.as_view(), name="listar_comentarios"),
    path('comentar', AddComment.as_view(), name="comentar"),
]

django_channels/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import (
    PasswordResetConfirmView, PasswordResetCompleteView
    )
from users.forms import PasswordConfirmForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls', namespace="base")),
    path('', include('users.urls')),
    path('chat/', include('chat.urls')),
    path('user/password/reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(template_name='user.passwordreset.confirm.html',
                                        success_url='/user/password/done/',
                                        form_class=PasswordConfirmForm
                                        ),
        name='password_reset_confirm',
    ),
    path(
        'user/password/done/',
        PasswordResetCompleteView.as_view(template_name='user.passwordreset.end.html'),
        name='pass_done',
    ),
]

users/urls.py
"""
Django Realtime Chat & Notifications
"""
## @package users.urls
#
# Urls de la aplicación participacion
# @version 1.0
from django.urls import path, reverse_lazy
from .views import *
from .forms import PasswordResetForm
from users import views
from django.contrib.auth.views import (
    PasswordResetView, PasswordResetDoneView,
	)

app_name = 'users'
urlpatterns = [
    path('login', LoginView.as_view(), name = "login"),
    path('logout', LogoutView.as_view(), name = "logout"),
    path('register', RegisterView.as_view(), name = "register"),
    path('account/password/reset/', PasswordResetView.as_view(
    								template_name='user.reset.html',
    								success_url=reverse_lazy('users:reset_done'),
    								form_class=PasswordResetForm),
    	name='forgot'),
    path('accounts/password/done/', PasswordResetDoneView.as_view(
    							   template_name='user.passwordreset.done.html'),
        name='reset_done'),
    path('account/change-pass/', ChangePasswordView.as_view(), name="change_pass"),
]

base/models.py
from django.db import models

# Create your models here.

base/views.py
"""
Django Realtime Chat & Notifications
"""
## @package base.views
#
# Vistas correspondientes a la aplicación base
# @version 1.0
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

    
class Inicio(LoginRequiredMixin,TemplateView):
    """!
    Clase para mostrar el inicio del sistema

    @date 24-04-2017
    @version 1.0.0
    """
    template_name = "inicio.html"

base/templates/base.alert.messages.html
{% for message in messages %}
    {% if message %}
        <!-- Modal Structure -->
        <div id="modal_msg" class="modal">
          <div class="modal-content">
            <h4>Aviso</h4>
            <p>{{ message }}</p>
          </div>
          <div class="modal-footer">
            <a href="#!" class="modal-action modal-close waves-effect btn teal">Aceptar</a>
          </div>
        </div>
        <script type="text/javascript">

            $(document).ready(function(){
                $('#modal_msg').modal();
                $('#modal_msg').modal('open');
              
            });
       
        </script>
    {% endif %}
{% endfor %}

base/templates/base.footer.html
<footer class="page-footer teal">
    <div class="">
        <div class="center">
            <p>
                <span id="year-info-develop">{% now "Y" %}</span>
            </p>
        </div>
    </div>
</footer>

base/templates/base.forms.errors.html
{% if form_errors %}
    <div class="error-notice">
        <div class="oaerror danger">
            <div class="row">
                <div class="{% if not col_title_error %}col s3{% else %}{{ col_title_error }}{% endif %}">
                    <strong>Error</strong>
                </div>
                <div class="{% if not col_msg_error %}col s9{% else %}{{ col_msg_error }}{% endif %}">
                    {% if custom_message_error %}{{ custom_message_error }}{% else %}{{ form_errors }}{% endif %}
                </div>
            </div>

        </div>
    </div>
{% endif %}

base/templates/base.nav.bar.html
<nav class="teal">
  <div class="nav-wrapper">
    <a class="brand-logo" href="{% url 'base:inicio' %}">Django Chat and Notifications</a>
    {% if request.user.is_authenticated %}
    <a href="#" data-activates="slide-out" class="button-collapse white-text"><i class="material-icons">menu</i></a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><a href="#!" class="dropdown-button" data-activates="dropdown1" data-beloworigin="true">Bienvenido <b>{{request.user.username}}</b> <i class="material-icons right">arrow_drop_down</i></a></li>
      <ul id='dropdown1' class='dropdown-content' data-belloworigin="true">
        <li><a href="{% url 'chat:chat' %}">Chat</a></li>
        <li><a href="{% url 'users:change_pass' %}">Cambiar Contraseña</a></li>
        <li><a href="{% url 'users:logout' %}">Logout</a></li>
      </ul>
    </ul>
    <a href="#" class="right not-button" data-activates="notification-out" >
      <i class="material-icons">notifications</i>
    </a> 
    {% else %}
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="#">Bienvenido <b>Anónimo</b></a></li>
      </ul>
    {% endif %}
  </div>
</nav>

base/templates/base.sidenav.html
<ul id="notification-out" class="side-nav">
  <li><a href="#!">First Sidebar Link</a></li>
  <li><a href="#!">Second Sidebar Link</a></li>
</ul>

base/templates/base.template.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset='UTF-8'>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
        <title>{% block title %}Django Notifications{% endblock %}</title>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">

        <link rel="stylesheet" type="text/css" href="{% static "materialize/css/materialize.min.css" %}"/>
        <link rel="stylesheet" type="text/css" href="{% static "materialize/material_icon/icon.css" %}"/>
        <link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}"/>
        
        <script src="{% static "jquery/jquery-3.1.0.min.js" %}"></script>
        <script src="{% static "materialize/js/materialize.min.js" %}"></script>
        <script src="{% static "js/funciones.js" %}"></script>
        {% block headScript %}{%endblock%}
    </head>
    <body class="grey lighten-4">
        {% include 'base.nav.bar.html' %}
        <main>
        {% include 'base.sidenav.html' %}
        {% block superContent%}
            <div class="container">
                <div class="card-panel">
                    {% block content %}{% endblock %}
                </div>
            </div>
        {% endblock %}
        </main>
        {% block modals %}{% endblock %}
        {% include 'base.footer.html' %}
    </body>
    {% block extraJs %}{%endblock%}
    {% include 'base.alert.messages.html' %}
    {% include 'base.vars.javascript.html' %}
</html>

base/templates/base.vars.javascript.html
<script type="text/javascript">

  // URL para el listado de comentarios
  var URL_LIST_COMMENT = "{% url 'chat:listar_comentarios' %}"

  // URL para crear comentarios
  var URL_CREATE_COMMENT = "{% url 'chat:comentar' %}"
    
</script>
    

base/templates/inicio.html
{% extends 'base.template.html' %}
{% load staticfiles %}
{% block title %}Inicio{% endblock %}
{% block content %}
    <div class="center">
        <p>Bienvenido a la aplicación de chat en tiempo real y notificaciones
          con <b>Django</b></p>
    </div>
{% endblock %}