base/urls.py
"""
Django Realtime Chat & Notifications
"""
## @package users.urls
#
# Urls de la aplicación participacion
# @version 1.0
from django.urls import path
from .views import *

app_name = 'base'
urlpatterns = [
    path('', Inicio.as_view(), name = "inicio")
]

chat/urls.py
"""
Django Realtime Chat & Notifications
"""
## @package chat.urls
#
# Urls de la aplicación participacion
# @version 1.0
from django.urls import path
from .views import *

app_name = 'chat'
urlpatterns = [
    path('', ChatView.as_view(), name = "chat"),
    path('listar-comentarios', ListComment.as_view(), name="listar_comentarios"),
    path('comentar', AddComment.as_view(), name="comentar"),
]

django_channels/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import (
    PasswordResetConfirmView, PasswordResetCompleteView
    )
from users.forms import PasswordConfirmForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls', namespace="base")),
    path('', include('users.urls')),
    path('chat/', include('chat.urls')),
    path('user/password/reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(template_name='user.passwordreset.confirm.html',
                                        success_url='/user/password/done/',
                                        form_class=PasswordConfirmForm
                                        ),
        name='password_reset_confirm',
    ),
    path(
        'user/password/done/',
        PasswordResetCompleteView.as_view(template_name='user.passwordreset.end.html'),
        name='pass_done',
    ),
]

chat/models.py
"""
Django Realtime Chat & Notifications
"""
## @package chat.models
#
# Modelos de la aplicación chat
# @author Leonel Hernández (leonelphm at gmail)
# @author Rodrigo Boet (rudmanmrrod at gmail)
# @version 1.0
from django.contrib.auth.models import User
from django.db import models

class Comentario(models.Model):
    """!
    Clase que contiene los datos de los Comentarios

    @author Ing. Leonel P. Hernandez M. (leonelphm at gmail)
    @copyright MIT
    @date 07-03-2018
    @version 1.0.0
    """
    fk_user_emite = models.ForeignKey(User, related_name='usurio_emite', on_delete=models.CASCADE)
    fk_user_recibe = models.ForeignKey(User, related_name='usurio_recibe', on_delete=models.CASCADE)
    comentario = models.TextField()
    fecha = models.DateTimeField(auto_now_add=True)
    visible = models.BooleanField(default=True)
    visto = models.BooleanField(default=False)

    class Meta:
        """!
            Clase que construye los meta datos del modelo
        """
        ordering = ('fecha',)
        verbose_name = 'Comentario'
        verbose_name_plural = 'Comentarios'
        db_table = 'chat_comentario'

    def __str__(self):
        """!
        Función que muestra el comentario

        @return Devuelve el comentario
        """
        return self.comentario

chat/forms.py
"""
Django Realtime Chat & Notifications
"""
## @package chat.forms
#
# Formularios correspondientes a la aplicación chat
# @version 1.0
from django import forms

class ChatSendForm(forms.Form):
  """!
  Clase que gestiona el formulario del envio en el chat

  @date 07-03-2018
  @version 1.0.0
  """ 

  ## Mensaje
  comentario = forms.CharField()

chat/views.py
"""
Django Realtime Chat & Notifications
"""
## @package chat.views
#
# Vistas correspondientes a la aplicación chat
# @author Leonel Hernández (leonelphm at gmail)
# @author Rodrigo Boet (rudmanmrrod at gmail)
# @version 1.0
from django.core import serializers
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import JsonResponse
from django.views import View
from django.views.generic import FormView

from .forms import ChatSendForm
from .models import Comentario


class ChatView(LoginRequiredMixin, FormView):
    """!
    Clase que gestiona la vista del chat

    @date 07-03-2018
    @version 1.0.0
    """
    template_name = "chat.template.html"
    form_class = ChatSendForm

    def get_context_data(self, **kwargs):
        """!
        Metodo que permite cargar de nuevo valores en los datos de contexto de la vista

        @date 07-03-2018
        @param self <b>{object}</b> Objeto que instancia la clase
        @param kwargs <b>{object}</b> Objeto que contiene los datos de contexto
        @return Retorna los datos de contexto
        """
        kwargs['users'] = User.objects.exclude(username=self.request.user.username).all()
        return super().get_context_data(**kwargs)

class ListComment(View):
    """!
    Clase que gestiona la lista de los comentarios

    @date 07-03-2018
    @version 1.0.0
    """
    def get(self, request, **kwargs):
        usuario_emite = request.user.pk
        usuario_recibe = request.GET.get('user_reci')
        serialized_object = None
        if usuario_emite is not None and usuario_recibe is not None:
            comentarios = Comentario.objects.filter(
                Q(fk_user_emite=usuario_emite, fk_user_recibe=usuario_recibe)  |  
                Q(fk_user_emite=usuario_recibe,fk_user_recibe=usuario_emite)).all(
                ).order_by('fecha')
            serialized_object = serializers.serialize('json', comentarios)

        return JsonResponse(serialized_object, safe=False)


class AddComment(View):
    """!
    Clase que gestiona el agregardo de los comentarios

    @date 07-03-2018
    @version 1.0.0
    """
    def post(self, request, **kwargs):
        comentario = request.POST.get('comentario')
        usuario_emite = request.POST.get('user_emite')
        usuario_recibe = request.POST.get('user_recibe')
        try:
            user_rec = User.objects.get(pk=usuario_recibe)
            user_emit = User.objects.get(pk=usuario_emite)
        except Exception as e:
            print(e)
            user_rec = None
            user_emit = None
        serialized_object = None
        if usuario_emite is not None and usuario_recibe is not None:
            try:
                comment = Comentario()
                comment.fk_user_emite = user_emit
                comment.fk_user_recibe = user_rec
                comment.comentario = comentario
                comment.save()
                serialized_object = serializers.serialize('json', [comment])
            except Exception as e:
                print(e)
                serialized_object = {'error': 'Fallo el envio de mensaje'}

        return JsonResponse(serialized_object, safe=False)

chat/templates/chat.template.html
{% extends 'base.template.html' %}
{% load staticfiles %}
{% block title %}Chat{% endblock %}
{% block content %}
    <div class="row">
      <div class="col m2">
        <div class="row center">Usuarios</div><hr/>
        {% for user in users %}
          <div class="row">
            <a href="#" onclick="get_comment({{user.id}},{{request.user.id}})">
              {{user.username}} <span class="badge" id="mesages" user-id="{{user.id}}">0</span>
            </a>
          </div>
        {% endfor %}
      </div>
      <div class="col m10">
        <div class="row center">Chat</div><hr/>
        <div class="chat-log">
        </div>
        <div class="chat-box" style="display:none;">
          {% csrf_token %}
          <input type="hidden" id="user_to"/>
          <div class="col m10">
            <div class="input-field {% if form.comentario.errors %}invalid{% endif %}">
                  {{ form.comentario }}
                  <label for="icon_prefix {{ form.comentario.auto_id }}">Mensaje</label>
                  {% include 'base.forms.errors.html' with form_errors=form.comentario.errors col_title_error='col s2' col_msg_error='col s10' %}
              </div>
          </div>
          <div class="col m2">
            <button class="btn-floating btn-large" id="send" onclick="testMsg()">
              <i class="tiny material-icons prefix">send</i>
            </button>
          </div>
        </div>
      </div>
    </div>
{% endblock %}
{% block extraJs %}
<script>
  var chatSocket = new WebSocket(
  'ws://' + window.location.host + '/chat/');

  chatSocket.onmessage = function(e) {
    var data = JSON.parse(e.data);
    if((data.fk_user_recibe==$("#user_to").val() && data.fk_user_emite=="{{user.id}}")
      || (data.fk_user_emite==$("#user_to").val() && data.fk_user_recibe=="{{user.id}}") )
    {
      var send = data.visto ? 'done_all' :'done';
      //var comment = value.fields.visible ? datos.comentario :'Este mensaje fue eliminado';
      if(data.fk_user_emite=="{{user.id}}")
      {
        var position = "sended right";
        send = 'done_all';
      }
      else{
        var position = "recived left";
      }
      var html = '<div class="row">';
      html += '<div class="'+position+'">'+data.comentario;
      html += '<br/><i class="tiny material-icons prefix">'+send+'</i> | ';
      html += '<small>'+ data.fecha +'</small></div>';
      html += '</div>';
      $('.chat-log').append(html);
      //$('.chat-log').scrollTop($('.chat-log').scrollTop()+100)
    }
  };

  chatSocket.onopen = function(e) {
    console.info('Chat socket conected');
  };

  chatSocket.onclose = function(e) {
    console.error('Chat socket closed unexpectedly');
  };

  function testMsg(){
    var token = $('input').val()
    var user_to = $('#user_to').val()
    var comentario = $('#id_comentario').val();
    if (comentario!=''){
      sendMessage(token,'{{user.id}}',user_to,comentario)
    }
  }
</script>
{%endblock%}